sudo: false
language: node_js
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      node_js: "8"
    - os: linux
      dist: trusty
      sudo: false
      node_js: "9"
    - os: linux
      dist: trusty
      sudo: false
      node_js: "10"
    - os: osx
      osx_image: xcode9.4
      node_js: "8"
    - os: osx
      osx_image: xcode9.4
      node_js: "9"
    - os: osx
      osx_image: xcode9.4
      node_js: "10"
install:
  - yarn
script:
  - yarn test
