sudo: false
language: node_js
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      node_js: "10"
install:
  - yarn
script:
  - yarn test
after_success:
  - yarn report-coverage
